# VS Code plugins
42Crunch.vscode-openapi
Arjun.swagger-viewer
bungcip.better-toml
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
ms-azuretools.vscode-docker
ms-python.python
redhat.vscode-yaml
rust-lang.rust
serayuzgur.crates
stoplight.spectral
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-russian
vadimcn.vscode-lldb
